import IdIcon from "assets/nav-icons/id.svg?react";
import ReportIcon from "assets/dualicons/forms.svg?react";
import {
  NAV_TYPE_ROOT,
  NAV_TYPE_ITEM,
  NAV_TYPE_COLLAPSE,
} from "constants/app.constant";

const ROOT_FORMS = "/reports";

const path = (root, item) => `${root}${item}`;

export const reports = {
  id: "reports",
  type: NAV_TYPE_ROOT,
  path: "reports",
  title: "Reports",
  transKey: "nav.reports.reports",
  Icon: ReportIcon,
  childs: [
    {
      id: "reports.purchase-reports",
      type: NAV_TYPE_COLLAPSE,
      path: path(ROOT_FORMS, "/purchase-reports"),
      title: "Purchase Reports",
      transKey: "nav.reports.purchase-reports",
      Icon: IdIcon,
      childs: [
        {
          id: "reports.product-wise-purchase",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/purchase-reports/product-wise-purchase"),
          title: "Product Wise Purchase",
          transKey: "nav.reports.product-wise-purchase",
        },
        {
          id: "reports.product-category-wise-purchase",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/purchase-reports/product-category-wise-purchase"),
          title: "Product Category Wise Purchase",
          transKey: "nav.reports.product-category-wise-purchase",
        },
        {
          id: "reports.purchase-order",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/purchase-reports/purchase-order"),
          title: "Purchase Order",
          transKey: "nav.reports.purchase-order",
        },
        {
          id: "reports.supplier-ledger",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/purchase-reports/supplier-ledger"),
          title: "Supplier Ledger",
          transKey: "nav.reports.supplier-ledger",
        },
        {
          id: "reports.supplier-purchase-summary",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/purchase-reports/supplier-purchase-summary"),
          title: "Supplier Purchase Summary",
          transKey: "nav.reports.supplier-purchase-summary",
        },
        {
          id: "reports.creditor-report",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/purchase-reports/creditor-report"),
          title: "Creditor Report",
          transKey: "nav.reports.creditor-report",
        },
        {
          id: "reports.daily-purchase-summary",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/purchase-reports/daily-purchase-summary"),
          title: "Daily Purchase Summary",
          transKey: "nav.reports.daily-purchase-summary",
        },
        {
          id: "reports.price-deviation",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/purchase-reports/price-deviation"),
          title: "Price Deviation",
          transKey: "nav.reports.price-deviation",
        },
      ],
    },
    {
      id: "reports.sales-reports",
      type: NAV_TYPE_COLLAPSE,
      path: path(ROOT_FORMS, "/sales-reports"),
      title: "Sales Reports",
      transKey: "nav.reports.sales-reports",
      Icon: IdIcon,
      childs: [
        {
          id: "reports.category-sales-summary",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/category-sales-summary"),
          title: "Category Sales Summary",
          transKey: "nav.reports.category-sales-summary",
        },
        {
          id: "reports.customer-sales-summary",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/customer-sales-summary"),
          title: "Customer Sales Summary",
          transKey: "nav.reports.customer-sales-summary",
        },
        {
          id: "reports.daily-sales-summary",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/daily-sales-summary"),
          title: "Daily Sales Summary",
          transKey: "nav.reports.daily-sales-summary",
        },
        {
          id: "reports.debtor-report",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/debtor-report"),
          title: "Debtor Report",
          transKey: "nav.reports.debtor-report",
        },
        {
          id: "reports.discount-report",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/discount-report"),
          title: "Discount Report",
          transKey: "nav.reports.discount-report",
        },
        {
          id: "reports.order-cancellation",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/order-cancellation"),
          title: "Order Cancellation",
          transKey: "nav.reports.order-cancellation",
        },
        {
          id: "reports.order-summary",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/order-summary"),
          title: "Order Summary",
          transKey: "nav.reports.order-summary",
        },
        {
          id: "reports.product-cancellation",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/product-cancellation"),
          title: "Product Cancellation",
          transKey: "nav.reports.product-cancellation",
        },
        {
          id: "reports.product-sales-summary",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/product-sales-summary"),
          title: "Product Sales Summary",
          transKey: "nav.reports.product-sales-summary",
        },
        {
          id: "reports.product-summary",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/product-summary"),
          title: "Product Summary",
          transKey: "nav.reports.product-summary",
        },
        {
          id: "reports.product-wise-order-details",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/product-wise-order-details"),
          title: "Product Wise Order Details",
          transKey: "nav.reports.product-wise-order-details",
        },
        {
          id: "reports.sales-receipt",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/sales-receipt"),
          title: "Sales Receipt",
          transKey: "nav.reports.sales-receipt",
        },
        {
          id: "reports.sales-summary",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/sales-reports/sales-summary"),
          title: "Sales Summary",
          transKey: "nav.reports.sales-summary",
        },
      ],
    },
    {
      id: "reports.stock-reports",
      type: NAV_TYPE_COLLAPSE,
      path: path(ROOT_FORMS, "/stock-reports"),
      title: "Stock Reports",
      transKey: "nav.reports.stock-reports",
      Icon: IdIcon,
      childs: [
        {
          id: "reports.current-stock-report",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/stock-reports/current-stock-report"),
          title: "Current Stock Report",
          transKey: "nav.reports.current-stock-report",
        },
        {
          id: "reports.daywise-stock-details",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/stock-reports/daywise-stock-details"),
          title: "Daywise Stock Details",
          transKey: "nav.reports.daywise-stock-details",
        },
        {
          id: "reports.reorder-level",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/stock-reports/reorder-level"),
          title: "Reorder Level",
          transKey: "nav.reports.reorder-level",
        },
        {
          id: "reports.stock-adjustment-report",
          type: NAV_TYPE_ITEM,
          path: path(ROOT_FORMS, "/stock-reports/stock-adjustment-report"),
          title: "Stock Adjustment Report",
          transKey: "nav.reports.stock-adjustment-report",
        },
      ],
    },
  ],
};
